const express = require('express');
const router = express.Router();
const { getOverview, getRequestsOverTime, getTopApis, getLatency } = require('../controllers/analyticsController');
const { protect } = require('../middleware/auth');
router.use(protect);
router.get('/overview', getOverview);
router.get('/requests', getRequestsOverTime);
router.get('/top-apis', getTopApis);
router.get('/latency', getLatency);
module.exports = router;
